export const VIETNAM_LOCATIONS = {
  호치민: {
    districts: [
      "Q1",
      "Q2",
      "Q3",
      "Q4",
      "Q5",
      "Q6",
      "Q7",
      "Q8",
      "Q9",
      "Q10",
      "Q11",
      "Q12",
      "Bình Thạnh",
      "Phú Nhuận",
      "Tân Bình",
      "Tân Phú",
      "Gò Vấp",
      "Bình Tân",
      "Thủ Đức",
      "기타",
    ],
    apartmentsByDistrict: {
      "Q1": [
        "Vinhomes Golden River",
        "Saigon Royal",
        "Grand Riverside",
        "Parkland Apartment",
        "Me Linh Point Tower",
        "The Manor",
        "Central Garden",
        "기타",
      ],
      "Q2": [
        "Vinhomes Central Park",
        "The Sun Avenue",
        "Masteri Thảo Điền",
        "Gateway Thảo Điền",
        "Estella Heights",
        "The Nassim",
        "Diamond Island",
        "Sala Sadora",
        "Sarimi Sala",
        "Vista Verde",
        "Lexington Residence",
        "Tropic Garden",
        "Ascent Thao Dien",
        "Xi Riverview Palace",
        "Masteri An Phú",
        "Palm Heights",
        "기타",
      ],
      "Q3": [
        "Vinhomes Bason",
        "Saigon Pavillon",
        "Botanic Tower",
        "Khánh Hội",
        "기타",
      ],
      "Q4": [
        "Rivergate Residence",
        "Saigon Pearl",
        "Sailing Tower",
        "기타",
      ],
      "Q5": ["기타"],
      "Q6": ["기타"],
      "Q7": [
        "Vinhomes Tan Cang",
        "Sunrise City",
        "Scenic Valley",
        "Phú Mỹ Hưng Midtown",
        "Happy Residence",
        "Sky Garden",
        "Era Town",
        "Riverside Residence",
        "Hoàng Anh Gia Lai",
        "Jamila Khang Điền",
        "기타",
      ],
      "Q8": [
        "Saigon South Residences",
        "Richmond City",
        "기타",
      ],
      "Q9": ["기타"],
      "Q10": ["기타"],
      "Q11": ["기타"],
      "Q12": ["기타"],
      "Bình Thạnh": [
        "Vinhomes Grand Park",
        "The Gold View",
        "Masteri Millennium",
        "The Tresor",
        "Dragon Hill",
        "City Garden",
        "The EverRich",
        "Saigon Gateway",
        "기타",
      ],
      "Tân Bình": [
        "Saigon Airport Plaza",
        "Hoa Sen",
        "Samland Riverside",
        "기타",
      ],
      "Thủ Đức": [
        "Vinhomes Grand Park",
        "Akari City",
        "Mizuki Park",
        "Safira Khang Điền",
        "Lovera Vista",
        "Gem Riverside",
        "Q7 Saigon Riverside",
        "기타",
      ],
      "Phú Nhuận": ["기타"],
      "Tân Phú": ["기타"],
      "Gò Vấp": ["기타"],
      "Bình Tân": ["기타"],
      "기타": ["기타"],
    },
  },
  하노이: {
    districts: [
      "Ba Đình",
      "Hoàn Kiếm",
      "Đống Đa",
      "Cầu Giấy",
      "Hai Bà Trưng",
      "Hoàng Mai",
      "Thanh Xuân",
      "Tây Hồ",
      "Long Biên",
      "Nam Từ Liêm",
      "Bắc Từ Liêm",
      "Hà Đông",
      "기타",
    ],
    apartmentsByDistrict: {
      "Ba Đình": [
        "Diplomatic Compound",
        "D'. Le Roi Soleil",
        "Lotte Center",
        "기타",
      ],
      "Hoàn Kiếm": ["Vincom Ba Trieu", "Indochina Plaza", "기타"],
      "Đống Đa": [
        "The Garden",
        "170 De La Thanh",
        "Golden Palace",
        "기타",
      ],
      "Cầu Giấy": [
        "Vinhomes Metropolis",
        "Starlake",
        "Sun Grand City",
        "Discovery Complex",
        "Golden Westlake",
        "Ciputra Hanoi",
        "기타",
      ],
      "Hai Bà Trưng": [
        "Times City",
        "Park Hill",
        "Vincom Center",
        "기타",
      ],
      "Thanh Xuân": [
        "Royal City",
        "The Manor Central Park",
        "Park View Residence",
        "N01T1 Ngoại Giao Đoàn",
        "기타",
      ],
      "Tây Hồ": [
        "Vinhomes Riverside",
        "Watermark",
        "Tay Ho Residence",
        "Xuan Dieu Street Area",
        "기타",
      ],
      "Nam Từ Liêm": [
        "Vinhomes Smart City",
        "Ecopark",
        "The K Park",
        "Home City",
        "기타",
      ],
      "Long Biên": ["Vinhomes Ocean Park", "Sài Đồng", "기타"],
      "Hoàng Mai": ["기타"],
      "Bắc Từ Liêm": ["기타"],
      "Hà Đông": ["기타"],
      "기타": ["기타"],
    },
  },
  다낭: {
    districts: [
      "Hải Châu",
      "Thanh Khê",
      "Sơn Trà",
      "Ngũ Hành Sơn",
      "Liên Chiểu",
      "Cẩm Lệ",
      "Hòa Vang",
      "기타",
    ],
    apartmentsByDistrict: {
      "Hải Châu": [
        "Azura Da Nang",
        "The Peak",
        "Vincom Center",
        "Indochina Riverside",
        "기타",
      ],
      "Thanh Khê": [
        "Monarchy Riverside",
        "Luxury Apartment",
        "Four Points by Sheraton",
        "기타",
      ],
      "Sơn Trà": [
        "Vinhomes Ocean Park",
        "Đà Nẵng Golden Bay",
        "Naman Residence",
        "Premier Sky Residences",
        "Olalani Resort & Condotel",
        "기타",
      ],
      "Ngũ Hành Sơn": [
        "Furama Resort",
        "Ariyana Smart Condotel",
        "Non Nuoc Beach Resort",
        "기타",
      ],
      "Liên Chiểu": ["기타"],
      "Cẩm Lệ": ["기타"],
      "Hòa Vang": ["기타"],
      "기타": ["기타"],
    },
  },
  냐짱: {
    districts: [
      "Vĩnh Hải",
      "Vĩnh Phước",
      "Phước Long",
      "Lộc Thọ",
      "Vĩnh Nguyên",
      "Phước Tân",
      "Phước Hòa",
      "Vạn Thạnh",
      "기타",
    ],
    apartmentsByDistrict: {
      "Vĩnh Hải": [
        "Vinhomes Marina",
        "Diamond Bay",
        "Condotel Nha Trang",
        "Charm Resort",
        "기타",
      ],
      "Vĩnh Phước": [
        "Muong Thanh Viễn Triều",
        "Golden Holiday",
        "Gold Coast",
        "기타",
      ],
      "Phước Long": [
        "Grand Torana",
        "The Anam",
        "Sheraton Nha Trang",
        "기타",
      ],
      "Lộc Thọ": ["Ana Marina", "Nha Trang Pearl", "기타"],
      "Vĩnh Nguyên": ["기타"],
      "Phước Tân": ["기타"],
      "Phước Hòa": ["기타"],
      "Vạn Thạnh": ["기타"],
      "기타": ["기타"],
    },
  },
  기타: {
    districts: ["기타"],
    apartmentsByDistrict: {
      "기타": ["기타"],
    },
  },
};

export const CITIES = Object.keys(VIETNAM_LOCATIONS);

// 도시별 구/군 가져오기
export const getDistrictsByCity = (city) => {
  return VIETNAM_LOCATIONS[city]?.districts || [];
};

// 구/군별 아파트 가져오기
export const getApartmentsByDistrict = (city, district) => {
  return VIETNAM_LOCATIONS[city]?.apartmentsByDistrict?.[district] || ["기타"];
};
