export const VIETNAM_LOCATIONS = {
  호치민: {
    districts: [
      "District 1 (Quận 1)",
      "District 2 (Quận 2 / Thủ Đức)",
      "District 3 (Quận 3)",
      "District 4 (Quận 4)",
      "District 5 (Quận 5)",
      "District 6 (Quận 6)",
      "District 7 (Quận 7)",
      "District 8 (Quận 8)",
      "District 9 (Quận 9)",
      "District 10 (Quận 10)",
      "District 11 (Quận 11)",
      "District 12 (Quận 12)",
      "Bình Thạnh (빈탄)",
      "Phú Nhuận (푸누언)",
      "Tân Bình (떤빈)",
      "Tân Phú (떤푸)",
      "Gò Vấp (고밥)",
      "Bình Tân (빈딴)",
      "Thủ Đức (투득)",
      "기타 지역",
    ],
    apartmentsByDistrict: {
      "District 1 (Quận 1)": [
        "Vinhomes Golden River",
        "Saigon Royal",
        "Grand Riverside",
        "Parkland Apartment",
        "Me Linh Point Tower",
        "The Manor",
        "Central Garden",
        "기타",
      ],
      "District 2 (Quận 2 / Thủ Đức)": [
        "Vinhomes Central Park",
        "The Sun Avenue",
        "Masteri Thảo Điền",
        "Gateway Thảo Điền",
        "Estella Heights",
        "The Nassim",
        "Diamond Island",
        "Sala Sadora",
        "Sarimi Sala",
        "Vista Verde",
        "Lexington Residence",
        "Tropic Garden",
        "Ascent Thao Dien",
        "Xi Riverview Palace",
        "Masteri An Phú",
        "Palm Heights",
        "기타",
      ],
      "District 3 (Quận 3)": [
        "Vinhomes Bason",
        "Saigon Pavillon",
        "Botanic Tower",
        "Khánh Hội",
        "기타",
      ],
      "District 4 (Quận 4)": [
        "Rivergate Residence",
        "Saigon Pearl",
        "Sailing Tower",
        "기타",
      ],
      "District 7 (Quận 7)": [
        "Vinhomes Tan Cang",
        "Sunrise City",
        "Scenic Valley",
        "Phú Mỹ Hưng Midtown",
        "Happy Residence",
        "Sky Garden",
        "Era Town",
        "Riverside Residence",
        "Hoàng Anh Gia Lai",
        "Jamila Khang Điền",
        "기타",
      ],
      "District 8 (Quận 8)": [
        "Saigon South Residences",
        "Richmond City",
        "기타",
      ],
      "Bình Thạnh (빈탄)": [
        "Vinhomes Grand Park",
        "The Gold View",
        "Masteri Millennium",
        "The Tresor",
        "Dragon Hill",
        "City Garden",
        "The EverRich",
        "Saigon Gateway",
        "기타",
      ],
      "Tân Bình (떤빈)": [
        "Saigon Airport Plaza",
        "Hoa Sen",
        "Samland Riverside",
        "기타",
      ],
      "Thủ Đức (투득)": [
        "Vinhomes Grand Park",
        "Akari City",
        "Mizuki Park",
        "Safira Khang Điền",
        "Lovera Vista",
        "Gem Riverside",
        "Q7 Saigon Riverside",
        "기타",
      ],
      "기타 지역": ["기타"],
    },
  },
  하노이: {
    districts: [
      "Ba Đình (바딘)",
      "Hoàn Kiếm (환끼엠)",
      "Đống Đa (동다)",
      "Cầu Giấy (까우저이)",
      "Hai Bà Trưng (하이바쭝)",
      "Hoàng Mai (황마이)",
      "Thanh Xuân (탄쑤언)",
      "Tây Hồ (따이호)",
      "Long Biên (롱비엔)",
      "Nam Từ Liêm (남뜨리엠)",
      "Bắc Từ Liêm (박뜨리엠)",
      "Hà Đông (하동)",
      "기타 지역",
    ],
    apartmentsByDistrict: {
      "Ba Đình (바딘)": [
        "Diplomatic Compound",
        "D'. Le Roi Soleil",
        "Lotte Center",
        "기타",
      ],
      "Hoàn Kiếm (환끼엠)": ["Vincom Ba Trieu", "Indochina Plaza", "기타"],
      "Đống Đa (동다)": [
        "The Garden",
        "170 De La Thanh",
        "Golden Palace",
        "기타",
      ],
      "Cầu Giấy (까우저이)": [
        "Vinhomes Metropolis",
        "Starlake",
        "Sun Grand City",
        "Discovery Complex",
        "Golden Westlake",
        "Ciputra Hanoi",
        "기타",
      ],
      "Hai Bà Trưng (하이바쭝)": [
        "Times City",
        "Park Hill",
        "Vincom Center",
        "기타",
      ],
      "Thanh Xuân (탄쑤언)": [
        "Royal City",
        "The Manor Central Park",
        "Park View Residence",
        "N01T1 Ngoại Giao Đoàn",
        "기타",
      ],
      "Tây Hồ (따이호)": [
        "Vinhomes Riverside",
        "Watermark",
        "Tay Ho Residence",
        "Xuan Dieu Street Area",
        "기타",
      ],
      "Nam Từ Liêm (남뜨리엠)": [
        "Vinhomes Smart City",
        "Ecopark",
        "The K Park",
        "Home City",
        "기타",
      ],
      "Long Biên (롱비엔)": ["Vinhomes Ocean Park", "Sài Đồng", "기타"],
      "기타 지역": ["기타"],
    },
  },
  다낭: {
    districts: [
      "Hải Châu (하이쩌우)",
      "Thanh Khê (탄케)",
      "Sơn Trà (손짜)",
      "Ngũ Hành Sơn (응우항선)",
      "Liên Chiểu (리엔찌에우)",
      "Cẩm Lệ (깜레)",
      "Hòa Vang (화방)",
      "기타 지역",
    ],
    apartmentsByDistrict: {
      "Hải Châu (하이쩌우)": [
        "Azura Da Nang",
        "The Peak",
        "Vincom Center",
        "Indochina Riverside",
        "기타",
      ],
      "Thanh Khê (탄케)": [
        "Monarchy Riverside",
        "Luxury Apartment",
        "Four Points by Sheraton",
        "기타",
      ],
      "Sơn Trà (손짜)": [
        "Vinhomes Ocean Park",
        "Đà Nẵng Golden Bay",
        "Naman Residence",
        "Premier Sky Residences",
        "Olalani Resort & Condotel",
        "기타",
      ],
      "Ngũ Hành Sơn (응우항선)": [
        "Furama Resort",
        "Ariyana Smart Condotel",
        "Non Nuoc Beach Resort",
        "기타",
      ],
      "기타 지역": ["기타"],
    },
  },
  냐짱: {
    districts: [
      "Vĩnh Hải (빈하이)",
      "Vĩnh Phước (빈푹)",
      "Phước Long (푹롱)",
      "Lộc Thọ (록토)",
      "Vĩnh Nguyên (빈응우옌)",
      "Phước Tân (푹딴)",
      "Phước Hòa (푹화)",
      "Vạn Thạnh (반탄)",
      "기타 지역",
    ],
    apartmentsByDistrict: {
      "Vĩnh Hải (빈하이)": [
        "Vinhomes Marina",
        "Diamond Bay",
        "Condotel Nha Trang",
        "Charm Resort",
        "기타",
      ],
      "Vĩnh Phước (빈푹)": [
        "Muong Thanh Viễn Triều",
        "Golden Holiday",
        "Gold Coast",
        "기타",
      ],
      "Phước Long (푹롱)": [
        "Grand Torana",
        "The Anam",
        "Sheraton Nha Trang",
        "기타",
      ],
      "Lộc Thọ (록토)": ["Ana Marina", "Nha Trang Pearl", "기타"],
      "기타 지역": ["기타"],
    },
  },
};

export const CITIES = Object.keys(VIETNAM_LOCATIONS);

// 도시별 구/군 가져오기
export const getDistrictsByCity = (city) => {
  return VIETNAM_LOCATIONS[city]?.districts || [];
};

// 구/군별 아파트 가져오기
export const getApartmentsByDistrict = (city, district) => {
  return VIETNAM_LOCATIONS[city]?.apartmentsByDistrict?.[district] || ["기타"];
};
